// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104163612_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Identity.EF.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiredat");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hashedtoken");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_refreshtokens");

                    b.HasIndex("HashedToken")
                        .IsUnique()
                        .HasDatabaseName("ix_refreshtokens_hashedtoken");

                    b.ToTable("refreshtokens", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResult", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("MaxDuration")
                        .HasColumnType("interval")
                        .HasColumnName("maxduration");

                    b.Property<bool>("NegativePoints")
                        .HasColumnType("boolean")
                        .HasColumnName("negativepoints");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("quizid");

                    b.Property<bool>("RandomAnswers")
                        .HasColumnType("boolean")
                        .HasColumnName("randomanswers");

                    b.Property<bool>("RandomQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("randomquestions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("userid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_quizresults");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quizresults_quizid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_quizresults_userid");

                    b.ToTable("quizresults", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultMultipleChoiceQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<float>("PointsPossibleToGet")
                        .HasColumnType("real")
                        .HasColumnName("pointspossibletoget");

                    b.Property<float>("ScoredPoints")
                        .HasColumnType("real")
                        .HasColumnName("scoredpoints");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No")
                        .HasName("pk_quizresultmultiplechoicequestions");

                    b.ToTable("quizresultmultiplechoicequestions", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultMultipleChoiceQuestionAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("SubNo")
                        .HasColumnType("integer")
                        .HasColumnName("subno");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("isselected");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No", "SubNo")
                        .HasName("pk_quizresultmultiplechoicequestionanswers");

                    b.ToTable("quizresultmultiplechoicequestionanswers", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultOpenQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("correctanswer");

                    b.Property<string>("GivenAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("givenanswer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<float>("PointsPossibleToGet")
                        .HasColumnType("real")
                        .HasColumnName("pointspossibletoget");

                    b.Property<float>("ScoredPoints")
                        .HasColumnType("real")
                        .HasColumnName("scoredpoints");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No")
                        .HasName("pk_quizresultopenquestions");

                    b.ToTable("quizresultopenquestions", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultSingleChoiceQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<float>("PointsPossibleToGet")
                        .HasColumnType("real")
                        .HasColumnName("pointspossibletoget");

                    b.Property<float>("ScoredPoints")
                        .HasColumnType("real")
                        .HasColumnName("scoredpoints");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No")
                        .HasName("pk_quizresultsinglechoicequestions");

                    b.ToTable("quizresultsinglechoicequestions", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultSingleChoiceQuestionAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("SubNo")
                        .HasColumnType("integer")
                        .HasColumnName("subno");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("isselected");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No", "SubNo")
                        .HasName("pk_quizresultsinglechoicequestionanswers");

                    b.ToTable("quizresultsinglechoicequestionanswers", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.Quiz", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ownerid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_quizzes_ownerid");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizMultipleChoiceQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No")
                        .HasName("pk_quizmultiplechoicequestions");

                    b.ToTable("quizmultiplechoicequestions", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizMultipleChoiceQuestionAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("SubNo")
                        .HasColumnType("integer")
                        .HasColumnName("subno");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No", "SubNo")
                        .HasName("pk_quizmultiplechoicequestionanswers");

                    b.ToTable("quizmultiplechoicequestionanswers", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizOpenQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("answer");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No")
                        .HasName("pk_quizopenquestions");

                    b.ToTable("quizopenquestions", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizSingleChoiceQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No")
                        .HasName("pk_quizsinglechoicequestions");

                    b.ToTable("quizsinglechoicequestions", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizSingleChoiceQuestionAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasColumnName("no");

                    b.Property<int>("SubNo")
                        .HasColumnType("integer")
                        .HasColumnName("subno");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("integer")
                        .HasColumnName("ordinalnumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id", "No", "SubNo")
                        .HasName("pk_quizsinglechoicequestionanswers");

                    b.ToTable("quizsinglechoicequestionanswers", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.SharedQuizzes.Models.SharedQuiz", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("character varying(36)")
                        .HasColumnName("quizid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sharedquizzes");

                    b.HasIndex("QuizId")
                        .IsUnique()
                        .HasDatabaseName("ix_sharedquizzes_quizid");

                    b.ToTable("sharedquizzes", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.SharedQuizzes.Models.SharedQuizUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id", "UserId")
                        .HasName("pk_sharedquizusers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sharedquizusers_userid");

                    b.ToTable("sharedquizusers", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.Users.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("hashedpassword");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResult", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizresults_quizzes_quizid");

                    b.HasOne("Domain.Modules.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizresults_users_userid");

                    b.OwnsOne("Common.Domain.ValueObjects.DateTimePeriod", "QuizRunningPeriod", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("quizrunningperiodend");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("quizrunningperiodstart");

                            b1.HasKey("Id")
                                .HasName("pk_quizresults");

                            b1.ToTable("quizresults");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizresults_quizresults_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "CreationInto", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("createdat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("createdbyuserid");

                            b1.HasKey("Id");

                            b1.ToTable("quizresults");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizresults_quizresults_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "RemovalInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removedat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("removedbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_quizresults");

                            b1.ToTable("quizresults");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizresults_quizresults_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "UpdateInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updateat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("updatebyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_quizresults");

                            b1.ToTable("quizresults");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizresults_quizresults_id");
                        });

                    b.Navigation("CreationInto")
                        .IsRequired();

                    b.Navigation("QuizRunningPeriod")
                        .IsRequired();

                    b.Navigation("RemovalInfo");

                    b.Navigation("UpdateInfo");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultMultipleChoiceQuestion", b =>
                {
                    b.HasOne("Domain.Modules.QuizResults.Models.QuizResult", null)
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizresultmultiplechoicequestions_quizresults_id");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultMultipleChoiceQuestionAnswer", b =>
                {
                    b.HasOne("Domain.Modules.QuizResults.Models.QuizResultMultipleChoiceQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("Id", "No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizresultmultiplechoicequestionanswers_quizresultmultiplec~");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultOpenQuestion", b =>
                {
                    b.HasOne("Domain.Modules.QuizResults.Models.QuizResult", null)
                        .WithMany("OpenQuestions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizresultopenquestions_quizresults_id");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultSingleChoiceQuestion", b =>
                {
                    b.HasOne("Domain.Modules.QuizResults.Models.QuizResult", null)
                        .WithMany("SingleChoiceQuestions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizresultsinglechoicequestions_quizresults_id");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultSingleChoiceQuestionAnswer", b =>
                {
                    b.HasOne("Domain.Modules.QuizResults.Models.QuizResultSingleChoiceQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("Id", "No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizresultsinglechoicequestionanswers_quizresultsinglechoic~");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.Quiz", b =>
                {
                    b.HasOne("Domain.Modules.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_users_ownerid");

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "CreationInto", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("createdat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("createdbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_quizzes");

                            b1.ToTable("quizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizzes_quizzes_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "RemovalInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removedat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("removedbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_quizzes");

                            b1.ToTable("quizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizzes_quizzes_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "UpdateInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updateat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("updatebyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_quizzes");

                            b1.ToTable("quizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_quizzes_quizzes_id");
                        });

                    b.OwnsOne("Domain.Modules.Quizzes.ValueObjects.QuizSettings", "Settings", b1 =>
                        {
                            b1.Property<string>("QuizId")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<int>("CopyMode")
                                .HasColumnType("integer")
                                .HasColumnName("copymode");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval")
                                .HasColumnName("duration");

                            b1.Property<bool>("NegativePoints")
                                .HasColumnType("boolean")
                                .HasColumnName("negativepoints");

                            b1.Property<int>("QuestionsCountInRunningQuiz")
                                .HasColumnType("integer")
                                .HasColumnName("questionscountinrunningquiz");

                            b1.Property<bool>("RandomAnswers")
                                .HasColumnType("boolean")
                                .HasColumnName("randomanswers");

                            b1.Property<bool>("RandomQuestions")
                                .HasColumnType("boolean")
                                .HasColumnName("randomquestions");

                            b1.HasKey("QuizId");

                            b1.ToTable("quizzes");

                            b1.WithOwner()
                                .HasForeignKey("QuizId")
                                .HasConstraintName("fk_quizzes_quizzes_id");
                        });

                    b.Navigation("CreationInto")
                        .IsRequired();

                    b.Navigation("RemovalInfo");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("UpdateInfo");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizMultipleChoiceQuestion", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.Quiz", null)
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizmultiplechoicequestions_quizzes_id");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizMultipleChoiceQuestionAnswer", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.QuizMultipleChoiceQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("Id", "No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizmultiplechoicequestionanswers_quizmultiplechoicequestio~");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizOpenQuestion", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.Quiz", null)
                        .WithMany("OpenQuestions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizopenquestions_quizzes_id");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizSingleChoiceQuestion", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.Quiz", null)
                        .WithMany("SingleChoiceQuestions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizsinglechoicequestions_quizzes_id");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizSingleChoiceQuestionAnswer", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.QuizSingleChoiceQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("Id", "No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quizsinglechoicequestionanswers_quizsinglechoicequestions_i~");
                });

            modelBuilder.Entity("Domain.Modules.SharedQuizzes.Models.SharedQuiz", b =>
                {
                    b.HasOne("Domain.Modules.Quizzes.Models.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sharedquizzes_quizzes_quizid");

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "CreationInto", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("createdat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("createdbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_sharedquizzes");

                            b1.ToTable("sharedquizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_sharedquizzes_sharedquizzes_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "RemovalInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removedat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("removedbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_sharedquizzes");

                            b1.ToTable("sharedquizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_sharedquizzes_sharedquizzes_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "UpdateInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updateat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("updatebyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_sharedquizzes");

                            b1.ToTable("sharedquizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_sharedquizzes_sharedquizzes_id");
                        });

                    b.Navigation("CreationInto")
                        .IsRequired();

                    b.Navigation("RemovalInfo");

                    b.Navigation("UpdateInfo");
                });

            modelBuilder.Entity("Domain.Modules.SharedQuizzes.Models.SharedQuizUser", b =>
                {
                    b.HasOne("Domain.Modules.SharedQuizzes.Models.SharedQuiz", null)
                        .WithMany("Users")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sharedquizusers_sharedquizzes_id");

                    b.HasOne("Domain.Modules.Users.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sharedquizusers_users_userid");
                });

            modelBuilder.Entity("Domain.Modules.Users.Models.User", b =>
                {
                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "CreationInto", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("createdat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("createdbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "RemovalInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removedat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("removedbyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.AggregateStateChangeInfo", "UpdateInfo", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<DateTime>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updateat");

                            b1.Property<string>("UserId")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("updatebyuserid");

                            b1.HasKey("Id")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("CreationInto");

                    b.Navigation("RemovalInfo");

                    b.Navigation("UpdateInfo");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResult", b =>
                {
                    b.Navigation("MultipleChoiceQuestions");

                    b.Navigation("OpenQuestions");

                    b.Navigation("SingleChoiceQuestions");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultMultipleChoiceQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Modules.QuizResults.Models.QuizResultSingleChoiceQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.Quiz", b =>
                {
                    b.Navigation("MultipleChoiceQuestions");

                    b.Navigation("OpenQuestions");

                    b.Navigation("SingleChoiceQuestions");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizMultipleChoiceQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Modules.Quizzes.Models.QuizSingleChoiceQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Modules.SharedQuizzes.Models.SharedQuiz", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
